baseURL = 'https://wesleydeland.com/blog/'
languageCode = 'en-us'
title = 'Wesley Deland - Blog'
theme = 'PaperMod'
publishDir = 'blog'

[params.author]
  name = 'Wesley Deland'
  email = 'mail@wesleydeland.com'

[[menu.main]]
name = 'Home'
url = 'https://wesleydeland.github.io/'
